Feat/react router initial
tony1908/devf-gdl2-frontend pull request #1
Opened 2018-04-24 02:48 UTC by juliogontor

Configuration of react router and basic example

2018-04-25 23:24 UTC, tony1908 requested changes

2018-04-25 23:24 UTC, tony1908 commented on src/components/login/container/Login.js
> +        //this.props.dispatch(userActions.logout());
Why are these comments here?

2018-04-25 23:24 UTC, tony1908 commented on src/components/login/container/Login.js
> +          switch(fieldName) {
May be you can change this switch for something simpler.

2018-04-25 23:24 UTC, tony1908 commented on src/components/login/container/Login.js
> +function mapStateToProps(state) {
Are you using redux for this app?

2018-04-25 23:24 UTC, tony1908 commented on src/components/register/container/Register.js
> +        //this.setState({ [name]: value });
do you need this comment?

2018-04-25 23:24 UTC, tony1908 commented on src/components/register/container/Register.js
> +            //<Redirect to="/home"/>
if you're not using this component, remove it.

2018-04-25 23:24 UTC, tony1908 commented on src/components/register/container/Register.js
> +        const { dispatch } = this.props;
Are you using redux on this app.

2018-04-26 00:36 UTC, juliogontor commented on src/components/login/container/Login.js
> +          switch(fieldName) {
i'm using in register with one field (userName) more

2018-04-26 15:05 UTC, tony1908 approved these changes

2018-04-26 15:05 UTC, merged